# Generated by Django 4.1.3 on 2023-01-14 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipend', '0003_admin_admindb_comdb_rename_image_itemdb_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comdb',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prodb',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
