# Generated by Django 4.1.3 on 2023-01-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipend', '0005_rename_category_comdb_productname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comdb',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prodb',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
