# Generated by Django 4.1.3 on 2023-01-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipend', '0006_alter_comdb_price_alter_prodb_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodb',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
