# Generated by Django 4.1.3 on 2023-02-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipend', '0007_alter_prodb_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.IntegerField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
