# Generated by Django 4.1.3 on 2023-02-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipend', '0008_cartdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdb',
            name='companyname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cartdb',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pic'),
        ),
    ]
