# Generated by Django 4.1.3 on 2023-02-16 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipend', '0009_cartdb_companyname_cartdb_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartdb',
            name='image',
        ),
        migrations.AlterField(
            model_name='cartdb',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
